### ISSUE TITLE
bug with new units

### ISSUE THREAD

**Issue by dan-omniscience** [adam2314/linet3#401]
I added a new unit: "חודשי"
and when tried to create a new item or edit an existed item the new unit is not showing in the dropdown

I tried to change the name to english: "monthly" but still it doesn't show.

Linet version: 3.01218

**Comment by adam2314** [comment]
come on its a CSS thing, ive fixed in the git.
it will be on the update server next weak, i hope. meanwhile you can always use the keyboard to select it.

**Comment by aribhour** [comment]
Dan,
Pls don't make any attention to Adam's attitude with "come on" thing :-) 
He expects you to be more computer savvy user as a programmer but the truth is that in the end, every time we get informed about such annoying phenomena like you pointed out with this issue, the application improves and gets closer to what we wanted it to become: An excellent, efficient. good looking, useful and user friendly application.

**Comment by dan-omniscience** [comment]
Hey Ari,
it`s ok as a programmer I know how it fill, and if I had time to do a Q&A
as as a programmer I would probably add some more technical info, but in
this case I really just did it as a user and did not tried to find why it's
not working, as an end user, a css or php bug is still a bug. In the future
as I did in some other cases I will try and give some more technical info
if I get into issues.

Shabt Shalom

**Comment by aribhour** [comment]
Anyway, in the last comment, forgot to thank you for paying attention and letting us know. Keep on doing that!
Shabat Shalom.
